[default.extend-words]
mozumasu = "mozumasu"
shortcat = "shortcat"
iterm = "iterm"
args = "args"
cose = "cose"
ue = "ue"
ANC = "ANC"

[default]
detect = ["en", "ja"]
extend-ignore-re = ["<cmd>.+<cr>", "<leader>.+\"", "<leader>.+`"]
